# Generated by Django 4.2.2 on 2023-06-11 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('weight', models.DecimalField(decimal_places=3, max_digits=9)),
                ('power', models.CharField(max_length=100)),
                ('extinction_date', models.IntegerField(blank=True, help_text='Enter extinction date if animal extinct')),
            ],
        ),
    ]
