# Generated by Django 4.2.2 on 2023-06-11 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zooapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='extinction_date',
            field=models.IntegerField(blank=True, help_text='Enter extinction date if animal extinct', null=True),
        ),
    ]
